version: "3.3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - '3306'

volumes:
  db_data: