# Generated by Django 4.1.3 on 2022-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infapp', '0002_infapp_delete_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please define your pack with a title', max_length=100, null=True, verbose_name='PAck title here')),
                ('details', models.TextField(help_text='Please take notes on your pack here', max_length=1000, null=True, verbose_name='Pack notes here')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
