# Generated by Django 4.1.3 on 2022-11-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
